import type { Content } from './types';
import { PlaceHolderImages } from './placeholder-images';

const getImageUrl = (id: string) => PlaceHolderImages.find(img => img.id === id)?.imageUrl || '';

export const contentData: Content[] = [
  {
    id: 'rec-1',
    title: 'Cybernetic Echo',
    type: 'movie',
    description: 'In a neon-drenched future, a detective hunts a rogue AI that has stolen the memories of his past, forcing him to question his own reality.',
    posterPath: getImageUrl('poster-1'),
    coverPath: getImageUrl('cover-1'),
    genres: ['Sci-Fi', 'Thriller'],
    rating: 8.5,
    duration: '2h 15min',
    cast: ['Keanu Reeves', 'Carrie-Anne Moss', 'Hugo Weaving'],
    releaseYear: 2023,
    isTrending: true,
  },
  {
    id: 'rec-2',
    title: 'The Last Laugh',
    type: 'tv',
    description: 'A struggling stand-up comedian discovers her jokes can alter reality. Her newfound power brings fame, but at a cost she never anticipated.',
    posterPath: getImageUrl('poster-2'),
    coverPath: getImageUrl('cover-2'),
    genres: ['Comedy', 'Fantasy'],
    rating: 9.1,
    duration: '8 Episodes',
    cast: ['Rachel Brosnahan', 'Bill Hader', 'Maya Rudolph'],
    releaseYear: 2024,
    isTrending: true,
  },
  {
    id: 'rec-3',
    title: 'Galaxy Drifters',
    type: 'movie',
    description: 'A ragtag crew of smugglers aboard the starship "Wanderer" takes on a high-stakes heist to save a planet from a tyrannical corporation.',
    posterPath: getImageUrl('poster-3'),
    coverPath: getImageUrl('cover-3'),
    genres: ['Sci-Fi', 'Action', 'Adventure'],
    rating: 8.8,
    duration: '2h 30min',
    cast: ['Chris Pratt', 'Zoe Saldana', 'Dave Bautista'],
    releaseYear: 2022,
    isTrending: true,
  },
  {
    id: 'rec-4',
    title: 'Shadows of Yesterday',
    type: 'tv',
    description: 'A private investigator in 1940s Los Angeles gets entangled in a web of conspiracy that reaches the highest levels of Hollywood.',
    posterPath: getImageUrl('poster-4'),
    coverPath: getImageUrl('cover-4'),
    genres: ['Mystery', 'Drama', 'Crime'],
    rating: 8.2,
    duration: '6 Episodes',
    cast: ['Humphrey Bogart', 'Lauren Bacall', 'Edward G. Robinson'],
    releaseYear: 2023,
  },
  {
    id: 'rec-5',
    title: 'Speed Demon',
    type: 'movie',
    description: 'A former getaway driver is pulled back into the criminal underworld for one last job, a high-speed race against time across the country.',
    posterPath: getImageUrl('poster-5'),
    coverPath: getImageUrl('cover-5'),
    genres: ['Action', 'Crime'],
    rating: 7.9,
    duration: '1h 58min',
    cast: ['Ryan Gosling', 'Idris Elba', 'Eiza González'],
    releaseYear: 2024,
    isTrending: true,
  },
  {
    id: 'rec-6',
    title: 'The Crimson Crown',
    type: 'tv',
    description: 'In a land of magic and monsters, a young queen must defend her throne from treacherous nobles and ancient evils.',
    posterPath: getImageUrl('poster-6'),
    coverPath: getImageUrl('cover-6'),
    genres: ['Fantasy', 'Adventure', 'Drama'],
    rating: 9.3,
    duration: '10 Episodes',
    cast: ['Anya Taylor-Joy', 'Henry Cavill', 'Michelle Yeoh'],
    releaseYear: 2023,
  },
  {
    id: 'rec-7',
    title: 'Parisian Hearts',
    type: 'movie',
    description: 'Two aspiring artists find love and inspiration in the enchanting streets of 1920s Paris, but their ambitions threaten to tear them apart.',
    posterPath: getImageUrl('poster-7'),
    coverPath: getImageUrl('cover-7'),
    genres: ['Romance', 'Drama'],
    rating: 8.1,
    duration: '2h 5min',
    cast: ['Emma Stone', 'Timothée Chalamet', 'Marion Cotillard'],
    releaseYear: 2022,
  },
  {
    id: 'rec-8',
    title: 'Day Zero',
    type: 'tv',
    description: 'A group of survivors navigates a post-apocalyptic world, facing not only the infected but also the darkness within humanity.',
    posterPath: getImageUrl('poster-8'),
    coverPath: getImageUrl('cover-8'),
    genres: ['Horror', 'Thriller', 'Drama'],
    rating: 8.7,
    duration: '9 Episodes',
    cast: ['Pedro Pascal', 'Bella Ramsey', 'Norman Reedus'],
    releaseYear: 2024,
  },
];
